# Generated by Django 5.0.6 on 2024-05-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exam_slug_lesson_slug_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
